console.log("Luis Anton P. Imperial")
console.log("2003")
console.log(2003)
console.log("Luis Imperial (2003)")
console.log("Luis", " Imperial ", "(2003)")
console.log("Luis")
console.log("Imperial")
console.log("(2003)")
console.log("Luis" + "Imperial" + "(2003)")
console.log("Luis " + "Imperial " + "(2003)")